import 'package:answers/models/answer.dart';

class Repository {
  final List<Answer> answers = [
    Answer('Evet'),
    Answer('Hayır'),
    Answer('Belki'),
    Answer('Zor'),
    Answer('Oldu Bil'),
    Answer('Tabii ki!'),
    Answer('Asla.'),
    Answer('Mümkün değil'),
    Answer('Yeter ki sen iste'),
    Answer('Bir bilene sormak lazım'),
    Answer('Kesinlikle'),
    Answer('%100 Olacak'),
    Answer('Biraz uğraşırsan, evet'),
    Answer('O işi unut'),
    Answer('Çok yakında'),
    Answer('Sabret'),
    Answer('Daha çok beklersin'),
    Answer('Olmaz olur mu hiç?'),
    Answer('Fazla vakit geçmeden yap!'),
    Answer('Bundan emin olabilirsin'),
    Answer('Biraz daha bekle'),
    Answer('Aslında bunu umursamıyorsun'),
    Answer('Bekle...'),
    Answer('HAHAHAHA hayır'),
    Answer('Dalga mı geçiyorsun?'),
    Answer('Böyle devam et.'),
    Answer('Elbette'),
    Answer('Elinden geleni yap'),
    Answer('Asla vazgeçme, olacak'),
    Answer('Elbet bir gün...'),
    Answer('Mümkün'),
    Answer('İmkansız'),
    Answer('Çok az kaldı'),
    Answer('Bence bunu sen de biliyorsun'),
    Answer('Başarıyla sonuçlanacak'),
    Answer('Biraz daha düşün'),
    Answer('Biraz zor'),
    Answer('Daha yolun var'),
    Answer('Desteğe ihtiyacın var'),
    Answer('Önemli Bir Çaba Gerekecek'),
    Answer('Aşırıya Kaçmayın'),
    Answer('Tereddüt Etmeyin'),
    Answer('Duygularınıza Kapılıp Kalmayın'),
    Answer('Şüphe Etme'),
    Answer('Üzerine Bahis Yapılmaz'),
    Answer('Saçmalama'),
    Answer('Bu Kadar Acele Etmeyin'),
    Answer('Endişelenme'),
    Answer('Bu Zamanda Daha Fazlasını Ummayın'),
    Answer('Erken Yap'),
    Answer('Bunu Daha Sonra Tartış'),
    Answer("10'a kadar say, Tekrar sor"),
    Answer('Bunu Bir Fırsat Olarak Görün'),
    Answer('İşbirliği Anahtar Olacak'),
    Answer('Beklemek Daha İyi'),
    Answer('Bunun üzerine bahse bile girerim'),
    Answer('Pratik ol'),
    Answer('Sabırlı ol'),
    Answer('Daha Cömert Olun'),
    Answer('Yardım, İlerlemenizi Başarıya Dönüştürür'),
    Answer('Babana sor'),
    Answer('Annene sormalısın'),
    Answer('Dikkatli Yaklaşın'),
    Answer('Önce Dinlenmene İzin Ver'),
    Answer('Maceracı Bir Tavır Benimseyin'),
    Answer('Rutinindeki Bu Değişikliği Kabul Et'),
    Answer('Kesinlikle hayır'),
    Answer('Bundan Bir Yıl Sonra Önemli Olmayacak'),
    Answer('Bu Zahmete Değer'),
    Answer('Belirsiz'),
    Answer('Bu Kesin'),
    Answer('Olağanüstü Olabilir'),
    Answer('Başarısız Olamaz'),
    Answer('Araştırın Ve Sonra Keyfini Çıkarın'),
    Answer('Eğer Direnmezsen'),
    Answer('Eğer Söyleneni Yaparsan'),
    Answer('İyi Yapılmışsa Tamam, Değilse, Hiç Yapmayın'),
    Answer('Sahip Olduğun Her Şeyi Ver'),
    Answer('Yazıya Dökün'),
    Answer('Daha Net Bir Görüş Alın'),
    Answer('İyi Niyetlerinizle Devam Edin'),
    Answer('Yükümlülüklerinizi Takip Edin'),
    Answer('Uzmanların Tavsiyelerine Uyun'),
    Answer('Başkasının Liderliğini Takip Edin'),
    Answer('Ev Hayatınıza Odaklanın'),
    Answer('Önce Başka Bir Şeyi Bitirin'),
    Answer('Şüphesiz'),
    Answer('Vakit Kaybetmeyin'),
    Answer('Bekleme'),
    Answer('Zor Olabilir Ama İçinde Değer Bulacaksınız'),
    Answer('Garantili Görünüyor'),
    Answer('Büyük Bir Zevkle Olacak'),
    Answer('İyi Şans Getirecek'),
    Answer('Bir Heyecan Yaratacağı Kesin'),
    Answer('Öngörülemez'),
    Answer('İşinize Odaklanmak Daha İyi Olabilir'),
    Answer('Tavsiye Edilmez'),
    Answer('Sana Pahalıya Mal Olacak'),
    Answer('Plan Yapmak İçin İyi Bir Zaman'),
    Answer('Harika Olacak'),
    Answer('Mücadeleye Değer Değil'),
    Answer('Gitme Zamanın Geldi'),
    Answer(''),
    Answer('Esnek Kalın'),
    Answer('İlgili Sorunlar Yüzeye Çıkabilir'),
    Answer('Yaklaşımınızı Yeniden Düşünün'),
    Answer('Çok Fazla Seçeneğin De Az Kadar Zor Olduğunu Anlayın'),
    Answer('Daha Rahat Bir Hızda İlerleyin'),
    Answer('Beklenmedik Duruma Hazırlanın'),
    Answer('Belki, Yaşlandığınızda'),
    Answer('Ayrıntılara Dikkat Edin'),
    Answer('Sadece Bir Kez Yapın'),
    Answer('Şimdi Yapabilirsin'),
    Answer('Yalnızsan Olmaz'),
    Answer('Herhalukarda'),
    Answer('Hiçbir Zaman'),
    Answer('Devam Et'),
    Answer('Aksilikler Yüksek Olasılıklı'),
    Answer('Daha Dikkatli Dinle; Anlayacaksın'),
    Answer('Bırak Gitsin'),
    Answer('Eski Çözümleri Geride Bırakın'),
    Answer('Aklını Yeni Fikirlere Açık Tut'),
    Answer('Durum Belirsiz'),
    Answer('Sonuç Olumlu Olacak'),
    Answer('Koşullar Çok Hızlı Değişecek'),
    Answer('Bu Şans Her Zaman Gelmez'),
    Answer('En İyi Çözüm Aşikar Çözüm Olmayabilir'),
    Answer('Cevap Size Başka Bir Dilde Gelebilir'),
    Answer('Cevap Arka Bahçenizde'),
    Answer('Bu Senin Kontrolün Dışında'),
    Answer('Bu Para İsrafı Olur'),
    Answer('Karar Vermek İçin Daha Fazla Zaman Ayırın'),
    Answer('Şansını Dene'),
    Answer('Sonucu Şaşırtıcı Olabilir'),
    Answer('Bunun hakkında Daha Fazla Konuş'),
    Answer('Odağınızı Değiştirin'),
    Answer('Önceliklerin Belirlenmesi Sürecin Gerekli Bir Parçası Olacaktır'),
    Answer('Daha Fazla Seçenek Arayın'),
    Answer('Enerjinizi Koruyun'),
    Answer('Kurallara Saygı Duyun'),
    Answer('Önemli Olanı Yeniden Önceliklendirin'),
    Answer('Kendi Engellerinizi Kaldırın'),
    Answer('Başka Bir Durumla Önemli Bir Bağlantı Var'),
    Answer('Başka Şeyleri Bırakmanız Gerekebilir'),
    Answer('Artık Eskisinden Daha İyi Biliyorsunuz'),
    Answer('Görmek için Çok Yakınsın'),
    Answer('Evet Ama Zorlama'),
    Answer('Ne Yaparsanız Yapın Sonuçlar Kalıcı Olacak'),
    Answer('Yürürken Adımınıza Dikkat Edin'),
    Answer('Daha İyi Bir Teklif İçin Bekleyin'),
    Answer('Bazen Beklemek Gerekir'),
    Answer('Hayal gücünü kullan'),
    Answer('Tartışmasız'),
    Answer('Bu Zamanda Olumsuz'),
    Answer('Daha Muhtemel Bir Çözüm Deneyin'),
    Answer('Orijinal Düşüncenize Güvenin'),
    Answer('Sezginize Güvenin'),
    Answer('En İyi Kararı Vermek İçin Sakin Olun'),
    Answer('Yeni Bir Plan Yapmak İçin İyi Bir Zaman'),
    Answer('Aşılması Gereken Engeller Olacak'),
    Answer('Garantisi Yok'),
    Answer('İyimser Olmak İçin İyi Bir Neden Var'),
    Answer('Mecbursun'),
    Answer('Şimdi Harekete Geçmelisiniz'),
    Answer('Hayal kırıklığına uğramayacaksın'),
    Answer('Yaptığın İçin Mutlu Olacaksın'),
    Answer('Daha Fazla Bilgiye İhtiyacınız Olacak'),
    Answer('Pişman Olacaksın'),
    Answer('Başka Yolları Düşünmeniz Gerekecek'),
    Answer('Muhalefet Edenler Olacak'),
  ];
}
